name: ci

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm

            - name: install dependencies
              run: npm ci

            - name: get nx commit sha
              uses: nrwl/nx-set-shas@v2
              with:
                  main-branch-name: master

            - name: lint
              run: npm run nx affected -- --target=lint --base=${{ env.NX_HEAD }}

            - name: test
              run: npm run nx affected -- --target=test --base=${{ env.NX_HEAD }}

            - name: build
              run: npm run nx affected -- --target=build --base=${{ env.NX_HEAD }}

    release:
        name: release
        runs-on: ubuntu-latest
        needs: [ci]
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
                  cache: npm

            - name: install dependencies
              run: npm ci

            - name: semantic release
              uses: cycjimmy/semantic-release-action@v2
              with:
                  semantic_version: 18
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/git
                  branches: master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: deploy
              run: npm run ng deploy
